//------------------------------------------------------------------------
// Copyright(c) 2024 My Plug-in Company.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"PlaitsVst.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"PlaitsVst VST3 (64Bit)"
#else
#define stringFileDescription	"PlaitsVst VST3"
#endif
#define stringCompanyName		"Fabian Deutschmann\0"
#define stringLegalCopyright	"Copyright(c) 2024 Fabian Deutschmann."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
